In [1]:
import numpy as np

In [2]:
A = np.array([[56,0,4.4,68]
             ,[1.2,104,52,8]
             ,[1.8,135,99,0.9]])


print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal = A.sum(axis=0)

print(cal)

[ 59.  239.  155.4  76.9]


In [4]:
percentage = A/cal.reshape(1,4)*100

print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [5]:
a = np.random.rand(5)

print(a)
print(a.T)

[0.52187137 0.23466182 0.58016953 0.21472343 0.45949565]
[0.52187137 0.23466182 0.58016953 0.21472343 0.45949565]


In [6]:
a = np.random.rand(5,1)

print(a)
print(a.T)

[[0.14517458]
 [0.50747139]
 [0.71660335]
 [0.86264045]
 [0.69830672]]
[[0.14517458 0.50747139 0.71660335 0.86264045 0.69830672]]


In [7]:
x = np.random.rand(8)

In [8]:
print(x.reshape(2,2,2))

[[[0.93936113 0.02429044]
  [0.35258868 0.19430628]]

 [[0.20836258 0.16218468]
  [0.46423358 0.15065188]]]


In [17]:
a = np.array([
    [2,1],
    [1,3]
])

In [18]:
np.dot(a,a)

array([[ 5,  5],
       [ 5, 10]])

In [21]:
d = np.random.rand(3,3)*50

d

array([[28.44788935,  8.47122034, 25.9909751 ],
       [13.54074006, 41.04337   , 17.72625232],
       [37.52027073,  1.27361636, 10.16735389]])

In [22]:
d.T

array([[28.44788935, 13.54074006, 37.52027073],
       [ 8.47122034, 41.04337   ,  1.27361636],
       [25.9909751 , 17.72625232, 10.16735389]])